# theme: minima
title: Leonardo Lima de Vasconcellos - Web Developer
author: Leonardo Lima de Vasconcellos
description: My Portfolio
theme: jekyll-theme-minimal
show_downloads: true
logo: /assets/headshot.png
